In [1]:
import numpy as np

In [26]:
which_camera = 'hd_00_05'

In [27]:
# load hd_00_00's joints
results = np.load('D:\\bev_smpl_skeleton\\' + which_camera + '\\video_results.npz',allow_pickle=True)['results'][()]

In [28]:
loaded_length = len(results)

In [29]:
motion_file= 'D:\\bev_smpl_skeleton\\' + which_camera + '\\' + which_camera + '_HM36Joint.txt'

f = open(motion_file, "a")

for key_name in results:
    print(results[key_name]['joints'][0][54:].shape)
    # 取得human3.6m的17個關鍵點
    joint_points = results[key_name]['joints'][0][54:]
    print(joint_points)
    line = ",".join([str(v) for v in joint_points.flatten().tolist()])
    f.write(line + "\n")    
    print(line)

f.close()

(17, 3)
[[ 1.12047233e-01  8.31412315e-01  1.69742316e-01]
 [ 1.88307296e-02  4.17513788e-01  1.63841009e-01]
 [ 7.41081387e-02 -1.85229480e-02  1.24767803e-01]
 [-3.43248099e-02  1.77881718e-02 -1.40865102e-01]
 [-6.23247102e-02  4.54312563e-01 -6.72802702e-02]
 [ 8.33461992e-03  8.65620017e-01 -2.66440343e-02]
 [ 3.56977284e-02 -9.15589809e-01  1.62323207e-01]
 [ 1.39804870e-01 -7.00909495e-01  2.06362516e-01]
 [ 1.19048186e-01 -4.98943597e-01  5.63652292e-02]
 [ 1.35288322e-02 -4.97587770e-01 -1.70483321e-01]
 [-7.47933611e-02 -7.01837659e-01 -2.81260669e-01]
 [-1.10594489e-01 -9.38239574e-01 -2.34694809e-01]
 [ 6.74994141e-02 -5.09026051e-01 -6.09755479e-02]
 [ 1.28022563e-02 -6.90575242e-01 -3.77254039e-02]
 [ 1.97085142e-02 -5.84363937e-04 -8.29464570e-03]
 [ 5.27006909e-02 -2.69173414e-01 -4.04643267e-02]
 [-2.60882135e-02 -5.84737420e-01 -2.45511308e-02]]
0.1120472326874733,0.8314123153686523,0.16974231600761414,0.01883072964847088,0.41751378774642944,0.16384100914001465,0.0741

In [30]:
# 再次檢查筆數
f2 = open(motion_file, "r")
assert len(f2.readlines()) == loaded_length
f2.close()